package jelly.collaboration;

import jelly.User;
import jelly.project.*;

import java.util.*;

/**
 * @author Weslie
 */
public class Collaborator {

    /**
     * The collaborator ID (Database management)
     */
    private int idCollaborator;

    /**
     * Builds a Collaborator with a given project and user
     * Pre : Project and User must exist before calling the constructor
     * @param p     the Project associated to the Collaborator
     * @param u     the User associated to the Collaborator
     */
    public Collaborator(Project p, User u) {
        this.project = p;
        this.user = u;
    }

    /**
     * Builds a Collaborator with a given project and user with an ID generated by the database
     * @param idCollaborator    the ID generated by the database
     * @param p                 the Project associated to the Collaborator
     * @param u                 the User associated to the Collaborator
     */
    public Collaborator(int idCollaborator, Project p, User u) {
        this.idCollaborator = idCollaborator;
        this.project = p;
        this.user = user;
    }

    /**
     * The project associated to the collaboration
     */
    public Project project;

    /**
     * The user associated to the collaboration
     */
    public User user;

    /**
     * adds a Board to the collection of boards of the current project
     * with a name given in argument
     * @param boardName     the name of the board to set
     */
    public void addBoard(String boardName) {
        // TODO implement here
    }

    /**
     * the getter for the attribute project
     * @return the Project attribute project
     */
    public Project getProject() {
        return project;
    }

    /**
     * the setter for the attribute project
     * @param project Project to set
     */
    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * the getter for the attribute user
     * @return the User attribute user
     */
    public User getUser() {
        return user;
    }

    /**
     * the setter for the attribute user
     * @param user User to set
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * removes a given Board from the collection of boards of the current project
     * if the removal was successful, the Board to remove is returned
     * @param boardToRemove
     * @return Board
     */
    public Board removeBoard(Board boardToRemove) {
        // TODO implement here
        return null;
    }

    /**
     * adds a step to a Board from the collection of boards of the current project
     * with the name given in parameter
     * @param boardToAffect
     * @param stepName
     */
    public void addStep(Board boardToAffect, String stepName) {
        // TODO implement here
    }

    /**
     * removes a given step from the board given in parameter
     * returns the removed Step upon removal
     * @param stepToRemove
     * @return Step
     */
    public Step removeStep(Step stepToRemove, Board boardToAffect) {
        // TODO implement here
        return null;
    }

    /**
     * adds a Task to the collection of a given Step 
     * from the collection of a given Board 
     * in the collection of the current project
     * with a given name
     * @param boardToAffect
     * @param stepToAffect
     * @param taskName
     */
    public void addTask(Board boardToAffect, Step stepToAffect, String taskName) {
        // TODO implement here
    }

    /**
     * removes a Task from the collection of a given Step 
     * from the collection of a given Board 
     * in the collection of the current project
     * @param boardToAffect
     * @param stepToAffect
     * @param taskToRemove
     * @return Task
     */
    public Task removeTask(Board boardToAffect, Step stepToAffect, Task taskToRemove) {
        // TODO implement here
        return null;
    }

    /**
     * updates the state of a Task from the collection of a given Step 
     * from the collection of a given Board 
     * in the collection of the current project
     * @param boardToAffect
     * @param stepToAffect
     * @param taskToUpdate
     */
    public void updateStateTask(Board boardToAffect, Step stepToAffect, String taskToUpdate) {
        // TODO implement here
    }

}